// File: src/main/java/com/example/stocktracker/model/StockSignal.java
package com.example.stocktracker.model;

/**
 * StockSignal represents a stock's trading signal.
 * It contains the stock symbol, name, current price, and the trading signal (Buy, Sell, Hold).
 */
@Data
public class StockSignal {
    private String symbol;
    private String name;
    private double price;
    private String signal;

    public StockSignal(String symbol, String name, double price, String signal) {
        this.symbol = symbol;
        this.name = name;
        this.price = price;
        this.signal = signal;
    }
    // Getters and setters can be generated by Lombok's @Data annotation

}